### ISSUE TITLE
vmware-infra-metrics-collector stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by thadjennings** [ManageIQ/manageiq-pods#494]
@miq-bot add_label bug

**What steps did you take and what happened:**
Podified CloudForms installed (latest as of May 7th). Configured VMware Compute Infrastructure Provider, but after 18 hours, nothing is being discovered.
As shown below, vmware-infra-metrics-collector is stuck in CrashLoopBackOff
```
 kubectl get pods
NAME                                                READY   STATUS             RESTARTS   AGE
1-ems-metrics-processor-f5c5d5bfd-7rmv7             1/1     Running            0          21h
1-ems-metrics-processor-f5c5d5bfd-znm2d             1/1     Running            0          21h
1-event-handler-fcd7b979-2c27t                      1/1     Running            0          4d21h
1-generic-5677648978-gj98t                          1/1     Running            1          4d21h
1-generic-5677648978-qcc5b                          1/1     Running            1          4d5h
1-priority-64f9578b4b-5nqlt                         1/1     Running            0          4d5h
1-priority-64f9578b4b-crqws                         1/1     Running            0          4d21h
1-remote-console-5774776dfc-jcmxm                   1/1     Running            0          4d5h
1-reporting-6585444cc6-hbhwn                        1/1     Running            0          4d5h
1-reporting-6585444cc6-hrcth                        1/1     Running            0          4d21h
1-schedule-64d4cc4468-57skf                         1/1     Running            0          4d21h
1-ui-6449b5dc4-4mlwd                                1/1     Running            0          4d21h
1-vmware-infra-event-catcher-2-5cf87c97b8-5686t     1/1     Running            0          23h
1-vmware-infra-metrics-collector-7bc6c8676d-d5q6t   0/1     CrashLoopBackOff   235        20h
1-vmware-infra-metrics-collector-7bc6c8676d-zxbg5   0/1     CrashLoopBackOff   235        20h
1-vmware-infra-operations-2-59c5bfb4dc-nmcxf        1/1     Running            0          23h
1-vmware-infra-refresh-2-6467c45bdc-tb77j           1/1     Running            8          23h
1-web-service-5d977fb45f-7k5cd                      1/1     Running            0          4d5h
httpd-575b54f66b-7pj4d                              1/1     Running            0          4d5h
kafka-5b57f47bf6-5dx76                              1/1     Running            2          4d5h
memcached-65c956867-v97rx                           1/1     Running            0          5d1h
orchestrator-5cc589778f-z968l                       1/1     Running            0          4d22h
postgresql-5c48d48f8-bm9sb                          1/1     Running            0          5d1h
zookeeper-55c6cbb8bc-rprhh                          1/1     Running            0          4d5h
```

Log is attached here --> 
[1-vmware-infra-metrics-collector-7bc6c8676d-zxbg5.log](https://github.com/ManageIQ/manageiq-pods/files/4617598/1-vmware-infra-metrics-collector-7bc6c8676d-zxbg5.log)

**Environment:**
- ManageIQ version: latest podified version as of 20200507
- Minikube/KIND/OCP version: OCP 4.3.8
- Kubernetes version: (use `kubectl version`): v1.16.2
- OS (e.g. from `/etc/os-release`): RHEL 7 and CoreOS 4.3

**Comment by chessbyte** [comment]
@agrare can you take a look at this issue?

**Comment by carbonin** [comment]
Thought this was fixed in https://github.com/ManageIQ/manageiq-providers-vmware/pull/572

I would ensure that you're using the most up to date images.

**Comment by agrare** [comment]
Yeah I think the worker image is out of date, here is the error:
```
app/models/manageiq/providers/vmware/infra_manager/metrics_collector_worker/runner.rb:3:in `do_before_work_loop': uninitialized constant ManageIQ::Providers::Vmware::InfraManager::MetricsCollectorWorker::Runner::MiqVim (NameError)
	from /var/www/miq/vmdb/app/models/miq_worker/runner.rb:108:in `prepare'
	from /var/www/miq/vmdb/app/models/miq_worker/runner.rb:94:in `start'
	from /var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:113:in `<main>'
```

Line 3 is the require: https://github.com/ManageIQ/manageiq-providers-vmware/blob/master/app/models/manageiq/providers/vmware/infra_manager/metrics_collector_worker/runner.rb#L3

**Comment by chessbyte** [comment]
@thadjennings Closing issue.  Please re-open if you are still having issues with a newer podified build.

**Comment by thadjennings** [comment]
Problem does not occur with the latest build.

**Comment by thadjennings** [comment]
Problem has reappeared in the latest build.
```
{"@timestamp":"2020-05-15T14:43:11.828312 ","hostname":"1-vmware-infra-metrics-collector-6477fbc6f6-2zffq","pid":7,"tid":"2af959f73960","level":"info","message":"---"}
{"@timestamp":"2020-05-15T14:43:11.828897 ","hostname":"1-vmware-infra-metrics-collector-6477fbc6f6-2zffq","pid":7,"tid":"2af959f73960","level":"info","message":"\n---\n:guid: 8c74631c-1fdc-442f-8bb6-e81562a13490"}
/opt/manageiq/bluecf-providers-vmware/app/models/manageiq/providers/vmware/infra_manager/metrics_collector_worker/runner.rb:3:in `do_before_work_loop': uninitialized constant ManageIQ::Providers::Vmware::InfraManager::MetricsCollectorWorker::Runner::MiqVim (NameError)
        from /var/www/miq/vmdb/app/models/miq_worker/runner.rb:108:in `prepare'
        from /var/www/miq/vmdb/app/models/miq_worker/runner.rb:94:in `start'
        from /var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:113:in `<main>'
{"@timestamp":"2020-05-15T14:43:11.835211 ","hostname":"1-vmware-infra-metrics-collector-6477fbc6f6-2zffq","pid":7,"tid":"2af959f73960","level":"debug","message":"PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 1, in use: 0, waiting_in_queue: 0"}
```

**Comment by agrare** [comment]
@thadjennings That sounds like a build issue?  If somehow it is deploying an old version of the code.

**Comment by carbonin** [comment]
@thadjennings you're running the wrong images.

Both master and jansa branches don't reference that constant on line 3 so it's effectively impossible to get the error you're posting with the latest code base in either of those releases.
