### ISSUE TITLE
Unable connect using "VM Console" function using WebMKS to take over console

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-pods#755]
I am running ManageIQ Kasparov and try to get the remote console (HTML5) working. 
First I have added the VMWare WebMKS files to the UI pods so I can use the WebMKS option.

When opening the console the console window opens but is unable to open the web socket connection for the console:

![image](https://user-images.githubusercontent.com/61044/134924332-fde8dde5-d2cc-4333-b26e-6640c0338c73.png)

Some investigation on the UI pod, the logs reveal the following error:
```
"level":"info","message":"Started GET \"/ws/console/7e2dae718c6dae00173ec30e3b66fb48\" for 127.0.0.1 at 2021-09-27 14:01:39 +0000"}
"level":"crit","message":"ActionController::RoutingError (No route matches [GET] \"/ws/console/7e2dae718c6dae00173ec30e3b66fb48\"):"}
"level":"crit","message":"actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
    actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
    railties (5.2.4.4) lib/rails/rack/logger.rb:28:in `call'
    actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
    rack (2.2.3) lib/rack/method_override.rb:24:in `call'
    rack (2.2.3) lib/rack/runtime.rb:22:in `call'
    activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
    rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
    secure_headers (3.9.0) lib/secure_headers/middleware.rb:12:in `call'
    railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
    puma (4.3.7) lib/puma/configuration.rb:228:in `call'
    puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
    puma (4.3.7) lib/puma/server.rb:472:in `process_client'
    puma (4.3.7) lib/puma/server.rb:328:in `block in run'
    puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"}
```

So I get an `No route matches [GET] \"/ws/console/7e2dae718c6dae00173ec30e3b66fb48\")` on the UI pod, what would make sense, because I would expect that this call would be redirected to the remote-console worker...

When following the log of the remote-console worker, there is no activity when opening the console.

I have inspected my httpd configuration but I cannot find why /ws/console/ is not redirected to the remote-console worker, but to the ui worker:

Content of `/etc/httpd/conf.d/application.conf `
```
Listen 8080

# Timeout: The number of seconds before receives and sends time out.
Timeout 120
ServerSignature Off
ServerTokens Prod

RewriteEngine On
Options SymLinksIfOwnerMatch

<VirtualHost *:8080>
  KeepAlive on
  # Without ServerName mod_auth_mellon compares against http:// and not https:// from the IdP
  ServerName https://%{REQUEST_HOST}

  ProxyPreserveHost on
  RequestHeader set Host miq-k-tst.vipernext.kpn.org
  RequestHeader set X-Forwarded-Host miq-k-tst.vipernext.kpn.org

  RewriteCond %{REQUEST_URI}     ^/ws/notifications [NC]
  RewriteCond %{HTTP:UPGRADE}    ^websocket$ [NC]
  RewriteCond %{HTTP:CONNECTION} ^Upgrade$   [NC]
  RewriteRule .* ws://ui:3000%{REQUEST_URI}  [P,QSA,L]
  ProxyPassReverse /ws/notifications ws://ui:3000/ws/notifications

  RewriteCond %{REQUEST_URI} !^/api

  # For httpd, some ErrorDocuments must by served by the httpd pod
  RewriteCond %{REQUEST_URI} !^/proxy_pages

  # For SAML /saml2 is only served by mod_auth_mellon in the httpd pod
  RewriteCond %{REQUEST_URI} !^/saml2

  # For OpenID-Connect /openid-connect is only served by mod_auth_openidc
  RewriteCond %{REQUEST_URI} !^/openid-connect

  RewriteRule ^/ http://ui:3000%{REQUEST_URI} [P,QSA,L]
  ProxyPassReverse / http://ui:3000/

  ProxyPass /api http://web-service:3000/api
  ProxyPassReverse /api http://web-service:3000/api

  RewriteCond %{REQUEST_URI}     ^/ws/console
  RewriteCond %{HTTP:UPGRADE}    ^websocket$  [NC]
  RewriteCond %{HTTP:CONNECTION} ^Upgrade$    [NC]
  RewriteRule .* ws://remote-console:3000%{REQUEST_URI}  [P,QSA,L]
  ProxyPassReverse /ws/console ws://remote-console:3000/ws/console

  # Ensures httpd stdout/stderr are seen by 'docker logs'.
  ErrorLog  "/dev/stderr"
  CustomLog "/dev/stdout" common
</VirtualHost>
```

Any suggestions?

ManageIQ version: Kasparov-1
- Running OKD 4.7
- Kubernetes version: v1.20

@miq-bot add-label bug

**Comment by evertmulder** [comment]
I upped the logging of mod_rewrite to see if I can pinpoint the issue:

```
[Mon Sep 27 14:36:34.848648 2021] [rewrite:trace2] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] init rewrite engine with requested uri /ws/console/1dad9db6fb8ef2420e182a249fbc6529
[Mon Sep 27 14:36:34.848689 2021] [rewrite:trace3] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] applying pattern '.*' to uri '/ws/console/1dad9db6fb8ef2420e182a249fbc6529'
[Mon Sep 27 14:36:34.848730 2021] [rewrite:trace4] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] RewriteCond: input='/ws/console/1dad9db6fb8ef2420e182a249fbc6529' pattern='^/ws/notifications' [NC] => not-matched
[Mon Sep 27 14:36:34.848734 2021] [rewrite:trace3] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] applying pattern '^/' to uri '/ws/console/1dad9db6fb8ef2420e182a249fbc6529'
[Mon Sep 27 14:36:34.848738 2021] [rewrite:trace4] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] RewriteCond: input='/ws/console/1dad9db6fb8ef2420e182a249fbc6529' pattern='!^/api' => matched
[Mon Sep 27 14:36:34.848742 2021] [rewrite:trace4] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] RewriteCond: input='/ws/console/1dad9db6fb8ef2420e182a249fbc6529' pattern='!^/proxy_pages' => matched
[Mon Sep 27 14:36:34.848745 2021] [rewrite:trace4] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] RewriteCond: input='/ws/console/1dad9db6fb8ef2420e182a249fbc6529' pattern='!^/saml2' => matched
[Mon Sep 27 14:36:34.848749 2021] [rewrite:trace4] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] RewriteCond: input='/ws/console/1dad9db6fb8ef2420e182a249fbc6529' pattern='!^/openid-connect' => matched
[Mon Sep 27 14:36:34.848752 2021] [rewrite:trace2] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] rewrite '/ws/console/1dad9db6fb8ef2420e182a249fbc6529' -> 'http://ui:3000/ws/console/1dad9db6fb8ef2420e182a249fbc6529'
[Mon Sep 27 14:36:34.848756 2021] [rewrite:trace2] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] forcing proxy-throughput with http://ui:3000/ws/console/1dad9db6fb8ef2420e182a249fbc6529
[Mon Sep 27 14:36:34.848760 2021] [rewrite:trace1] [pid 15:tid 139958530590464] mod_rewrite.c(482): [client 10.129.2.2:39530] 10.129.2.2 - - [miq-k-tst.vipernext.kpn.org/sid#55c5e8474860][rid#7f4a9c002c10/initial] go-ahead with proxy request proxy:http://ui:3000/ws/console/1dad9db6fb8ef2420e182a249fbc6529 [OK]
10.129.2.2 - - [27/Sep/2021:14:36:34 +0000] "GET /ws/console/1dad9db6fb8ef2420e182a249fbc6529 HTTP/1.1" 404 728
```

**Comment by evertmulder** [comment]
When also adding the missing keypair things start working:
![image](https://user-images.githubusercontent.com/61044/134935110-f8ed35b9-aeb9-45b3-871f-70a74d59b769.png)

I will create a PR for this issue.
1. for the operator generates and invalid httpd config
2. for the mounting of the keypair in the remote console worker pods

**Comment by Fryguy** [comment]
@bdunne Please review.

**Comment by bdunne** [comment]
I think this is resolved by https://github.com/ManageIQ/manageiq-pods/issues/829
