### ISSUE TITLE
[Podified on EKS] Rake command does not work with external DB

### ISSUE THREAD

**Issue by rabah-beldi** [ManageIQ/manageiq-pods#771]
I have installed manageiq pod on eks (database on a pod) and I encounter a problem with the import/export of objects via the rake command does not work. 

```
rake evm:export:service_dialogs -- --directory /tmp/export/
rake aborted!
Cannot load database configuration:
Could not load database configuration. No such file - ["config/database.yml"]
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application/configuration.rb:185:in `database_configuration'
/var/www/miq/vmdb/lib/patches/database_configuration_patch.rb:32:in `database_configuration'
/opt/manageiq/manageiq-gemset/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `each'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/opt/manageiq/manageiq-gemset/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'
/var/www/miq/vmdb/config/environment.rb:5:in `<top (required)>'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/manageiq/manageiq-gemset/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
Could not load database configuration. No such file - ["config/database.yml"]
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application/configuration.rb:185:in `database_configuration'
/var/www/miq/vmdb/lib/patches/database_configuration_patch.rb:32:in `database_configuration'
/opt/manageiq/manageiq-gemset/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `each'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/opt/manageiq/manageiq-gemset/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'
/var/www/miq/vmdb/config/environment.rb:5:in `<top (required)>'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/opt/manageiq/manageiq-gemset/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/manageiq/manageiq-gemset/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => evm:export:service_dialogs => environment
(See full trace by running task with --trace)
```

- ManageIQ version: Kasparov-1 
- Minikube/KIND/OCP/CRC version:
- Kubernetes version: (use `kubectl version`): k version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 

@miq-bot add-label bug

**Comment by Fryguy** [comment]
@rabah-beldi I assume you are getting a remote shell into an existing pod?  If so, then you need to first do:

```
cd /var/www/miq/vmdb
source ./container_env
```

This sets up certain environment variables that are needed in order to run commands

**Comment by rabah-beldi** [comment]
Hello @Fryguy ,
thank you for your quick response. it works well :)

thanks gain for your help.
